name: Release GitS

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: android 
            goarch: arm64
            ext: ""    
          - goos: windows
            goarch: amd64
            ext: ".exe"
          - goos: darwin
            goarch: amd64
            ext: ""
          - goos: darwin
            goarch: arm64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate Semantic Version
        id: auto_version
        run: |
          echo "RELEASE_VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: go mod download

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w" -o gits-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: gits-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          generate_release_notes: true